#ifndef _INSARC_H
#define _INSARC_H

#include "jkwindef.h"

#define InsaIconCount 42

enum InsaIconName{
	priup=0,
	pridn,
	sagoup,
	sagodn,
	oneup,
	onedn,
	bornup,
	borndn,
	eduup,
	edudn,
	reliup,
	relidn,
	bloodup,
	blooddn,
	gyegupup,
	gyegupdn,
	dutyup,
	dutydn,
	tkiup,
	tkidn,
	jagyukup,
	jagyukdn,
	weddingup,
	weddingdn,
	gunup,
	gundn,
	pantsup,
	pantsdn,
	shutsup,
	shutsdn,
	shoesup,
	shoesdn,
	kmpiup,
	kmpidn,
	birthup,
	birthdn,
	junyokup,
	junyokdn,
	junhyunup,
	junhyundn,
	exitup,
	exitdn
};

extern WORD InsaIconID[InsaIconCount];

#endif